# Identifying Linear Independence of Eigenvectors

## **Problem:**
How can we effectively calculate the eigenvalues and eigenvectors of a matrix  Moreover, how do we verify whether eigenvectors corresponding to distinct eigenvalues are independent?

### **Approach:**

In [2]:
#import header files
import numpy as np
import sympy


### **Define Matrix A:**
Matrix A represents the linear transformation that we want to analyze. It's a square matrix with dimensions corresponding to the number of dimensions in the space we're working with. In this case, it's a 3x3 matrix.

In [3]:
A = np.array([[2, 1, 0],
              [1, 3, -1],
              [0, -1, 4]])

## **Calculating Eigenvalues and Eigenvectors**
**Eigenvalues and eigenvectors** are fundamental concepts in linear algebra, providing insights into how matrices transform vectors in a vector space.
### **Eigenvalues**
**Eigenvalues** are scalar values that represent the scaling factor of the eigenvectors when the transformation represented by the matrix A is applied. We compute eigenvalues using the characteristic equation of the matrix A.
### **Eigenvectors**
**Eigenvectors** are vectors that remain in the same direction after the transformation represented by matrix A. We compute eigenvectors corresponding to each eigenvalue.


In [11]:
# Calculate eigenvalues and eigenvectors using NumPy
eigenvalues, eigenvectors = np.linalg.eig(A)
print(A)
print(eigenvalues)
print(eigenvectors)

[[ 2  1  0]
 [ 1  3 -1]
 [ 0 -1  4]]
[1.26794919 3.         4.73205081]
[[-0.78867513 -0.57735027 -0.21132487]
 [ 0.57735027 -0.57735027 -0.57735027]
 [ 0.21132487 -0.57735027  0.78867513]]


### **Checking for Distinct Eigenvalues**
 Distinct eigenvalues are crucial as they indicate how many linearly independent eigenvectors we have. Linear independence ensures that the eigenvectors represent different directions of transformation.

In [14]:
# Check if eigenvalues are distinct
if len(np.unique(eigenvalues)) != len(eigenvalues):
    print("Eigenvalues are not distinct.")
else:
    print("Eigenvalues are distinct.")

Eigenvalues are distinct.


### **Forming Eigenvectors Matrix**
If the eigenvalues are distinct, each eigenvalue will correspond to one or more eigenvectors. We organize these eigenvectors into a matrix where each column represents an eigenvector corresponding to a distinct eigenvalue.


In [15]:
# matrix with eigenvectors corresponding to distinct eigenvalues
eigenvectors_matrix = np.column_stack(eigenvectors)
print(eigenvectors_matrix)

[[-0.78867513  0.57735027  0.21132487]
 [-0.57735027 -0.57735027 -0.57735027]
 [-0.21132487 -0.57735027  0.78867513]]


### **Converting to RREF**
**Row echelon form (RREF)** standardizes the representation of matrices, making it easier to analyze their properties. By converting the eigenvectors matrix to RREF, we can determine whether the eigenvectors corresponding to distinct eigenvalues are linearly independent.

In [9]:
# Convert matrix to RREF using SymPy
rref_matrix, pivot_columns = sympy.Matrix(eigenvectors_matrix).rref()
print(rref_matrix)
print(pivot_columns)

Matrix([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
(0, 1, 2)


### **Verifying Independence**
In RREF, if every column containing a leading entry (pivot) corresponds to a distinct eigenvalue, it indicates that the eigenvectors associated with those eigenvalues are linearly independent. This is because each pivot column represents a linearly independent eigenvector, and having distinct pivots implies distinct eigenvalues. Therefore, if there are as many pivot columns as there are distinct eigenvalues, the eigenvectors are linearly independent.


In [10]:
# Check if RREF has full rank
if len(pivot_columns) == len(eigenvalues):
 print("Eigenvectors corresponding to distinct eigenvalues are independent.")
else:
 print("Eigenvectors corresponding to distinct eigenvalues are dependent.")


Eigenvectors corresponding to distinct eigenvalues are independent.
